### ISSUE TITLE
Issue in Swiss iban spec

### ISSUE THREAD

**Issue by dominikheeb** [close2/iban#12]
Hi

In the iban package is an error with the swiss iban specification.
The package wants the swiss iban to have a number at the last digit of the iban. Valid can also be a character.
see on this page:
https://www.ubs.com/ch/en/help/account/iban.html
Open segment: Where do I find the IBAN for my UBS account?

Could you update the specs to support ubs accounts as well?

Best regards

**Comment by close2** [comment]
The package does allow `X` in swiss ibans.

If you use the correct checksum (3rd and 4th character) the iban from ubs.com does work:
`CH640023023012345601X`
