### ISSUE TITLE
False negative for Hungarian IBAN

### ISSUE THREAD

**Issue by Pomis** [close2/iban#5]
https://www.citadele.lt/en/online-banking/examples/
HU4211773016111110180000000 returns false

**Comment by close2** [comment]
I think the example iban in www.citadele.lt is incorrect.
They say that a HU iban should have a length of 28 but the example given is only 27 characters long.

Please open an issue at https://github.com/arhs/iban.js if you still think that the given IBAN should work.
(I keep the definitions in sync with iban.js)

**Comment by Pomis** [comment]
Thank you
